# Generated by Django 4.1.4 on 2023-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
    ]
