# Generated by Django 4.1.4 on 2023-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_ward_isfull'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='occupancy',
            field=models.IntegerField(default=0),
        ),
    ]
