# Generated by Django 4.1.4 on 2023-01-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_ward_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='isFull',
        ),
    ]
