# Generated by Django 4.1.4 on 2023-01-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_ward_isfull'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='type',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
    ]
