# Generated by Django 4.1.7 on 2023-04-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_hospital_id_alter_ward_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='hospital',
        ),
    ]
