# Generated by Django 4.1.7 on 2023-04-07 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_ward_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
