# Generated by Django 4.1.7 on 2023-04-07 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_ward_ward_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='ward_id',
        ),
        migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
