# Generated by Django 4.1.4 on 2023-01-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_outpatient_outpatientreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
