# Generated by Django 4.1.4 on 2023-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_inpatient_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospitalStaff',
            field=models.BooleanField(default=False),
        ),
    ]
