# Generated by Django 4.1.4 on 2023-01-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_hospitalstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='inpatient',
            old_name='admitted_at',
            new_name='admittedAt',
        ),
        migrations.RenameField(
            model_name='outpatient',
            old_name='admitted_at',
            new_name='admittedAt',
        ),
        migrations.RenameField(
            model_name='outpatientreport',
            old_name='recorded_at',
            new_name='recordedAt',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date_updated',
            new_name='dateUpdated',
        ),
    ]
