# Generated by Django 4.1.4 on 2023-01-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_is_active_appointment_isactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
