# Generated by Django 4.1.4 on 2023-01-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_created_at_appointment_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inpatient',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='proffesion',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='patientRecord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.patientrecord'),
            preserve_default=False,
        ),
    ]
