# Generated by Django 4.1.4 on 2023-01-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_ward_occupancy'),
        ('user', '0009_alter_inpatient_options_alter_proffesion_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientRecord',
            new_name='Diagnosis',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='patientRecord',
            new_name='diagnosis',
        ),
    ]
