# Generated by Django 4.1.4 on 2023-01-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_admittedat_inpatient_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hospitalstaff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.inpatient')),
            ],
        ),
    ]
