# Generated by Django 4.1.4 on 2023-01-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_inpatientreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='hospital',
        ),
    ]
