# Generated by Django 4.1.4 on 2023-01-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_diagnosis_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.diagnosis'),
        ),
    ]
