# Generated by Django 4.1.4 on 2023-01-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_diagnosis_appointment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('isActive', 'createdAt')},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('isActive', 'createdAt')},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
