# Generated by Django 4.1.4 on 2023-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_appointment_options_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inpatientreport',
            options={'ordering': ('createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='outpatient',
            options={'ordering': ('isActive', 'createdAt')},
        ),
        migrations.AlterModelOptions(
            name='outpatientreport',
            options={'ordering': ('createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ('isActive', 'createdAt')},
        ),
        migrations.AddField(
            model_name='outpatient',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
