# Generated by Django 4.1.4 on 2023-01-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_inpatientreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatientreport',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.hospitalstaff'),
            preserve_default=False,
        ),
    ]
