# Generated by Django 4.1.4 on 2023-01-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_outpatientreport_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-isActive', 'createdAt')},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('-isActive', 'createdAt')},
        ),
        migrations.AlterModelOptions(
            name='outpatient',
            options={'ordering': ('-isActive', 'createdAt')},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ('-isActive', 'createdAt')},
        ),
    ]
