# Generated by Django 4.1.4 on 2023-01-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_rename_county_code_county_countycode_and_more'),
        ('user', '0018_alter_appointment_options_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='dischargedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hospitalstaff'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='made on'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='hospitalstaff',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registered on'),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='admitted on'),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Still Admitted'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='prescribed on'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registered on'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.subcounty', verbose_name='constituency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
