# Generated by Django 4.1.4 on 2023-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_inpatient_dischargedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='dischargedOn',
            field=models.DateTimeField(default=None, null=True, verbose_name='discharged on'),
        ),
    ]
