# Generated by Django 4.1.4 on 2023-01-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_inpatient_dischargedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='dischargedBy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hospitalstaff'),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='dischargedOn',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='discharged on'),
        ),
    ]
