# Generated by Django 4.1.4 on 2023-01-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_is_admin_alter_inpatient_dischargedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proffesion',
            name='area',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
