# Generated by Django 4.1.4 on 2023-01-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_proffesion_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proffesion',
            old_name='area',
            new_name='permission',
        ),
    ]
