# Generated by Django 4.1.4 on 2023-01-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0025_alter_proffesion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proffesion',
            name='permission',
        ),
        migrations.AddField(
            model_name='proffesion',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
