# Generated by Django 4.1.4 on 2023-01-21 21:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_inpatient_options_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profiles/default.jpg', upload_to=user.models.upload_profileImage),
        ),
    ]
