# Generated by Django 4.1.4 on 2023-01-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inpatient',
            options={'ordering': ('-isActive', 'createdAt')},
        ),
        migrations.AddField(
            model_name='outpatient',
            name='dischargedBy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hospitalstaff'),
        ),
        migrations.AddField(
            model_name='outpatient',
            name='dischargedOn',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='discharged on'),
        ),
    ]
