# Generated by Django 4.1.4 on 2023-01-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_inpatient_options_outpatient_dischargedby_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-isActive', '-createdAt')},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('-isActive', '-createdAt')},
        ),
        migrations.AlterModelOptions(
            name='inpatient',
            options={'ordering': ('-isActive', '-createdAt')},
        ),
        migrations.AlterModelOptions(
            name='inpatientreport',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='outpatient',
            options={'ordering': ('-isActive', '-createdAt')},
        ),
        migrations.AlterModelOptions(
            name='outpatientreport',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ('-isActive', '-createdAt')},
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='dischargedBy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hospitalstaff', verbose_name='discharged by'),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='dischargedBy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hospitalstaff', verbose_name='discharged by'),
        ),
    ]
