# Generated by Django 4.1.7 on 2023-03-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
