# Generated by Django 4.1.7 on 2023-04-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_remove_user_firstname_remove_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
