# Generated by Django 4.1.7 on 2023-04-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_remove_diagnosis_appointment_remove_diagnosis_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalstaff',
            name='hospital',
        ),
    ]
