# Generated by Django 4.1.7 on 2023-04-09 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_id_alter_diagnosis_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-isActive', '-appointmentDate', '-createdAt')},
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 8, 42, 59, 617705, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
