# Generated by Django 4.1.4 on 2023-01-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
