# Generated by Django 4.1.4 on 2023-01-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_subcounty_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='county_code',
            new_name='countyCode',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='county_name',
            new_name='countyName',
        ),
        migrations.RenameField(
            model_name='subcounty',
            old_name='subcounty_code',
            new_name='subcountyCode',
        ),
        migrations.RenameField(
            model_name='subcounty',
            old_name='subcounty_name',
            new_name='subcountyName',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='isActive',
        ),
    ]
