# Generated by Django 4.1.4 on 2023-01-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_rename_county_code_county_countycode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ('countyName',)},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'ordering': ('subcountyName',)},
        ),
    ]
