# Generated by Django 4.1.7 on 2023-03-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_county_options_alter_subcounty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcounty',
            options={'ordering': ('county__countyName', 'subcountyName')},
        ),
    ]
